# Generated by Django 4.0.4 on 2022-05-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day', models.IntegerField()),
                ('date_of_day', models.DateField()),
                ('hours', models.IntegerField()),
                ('starting_time', models.IntegerField(default=9)),
                ('ending_time', models.IntegerField(default=17)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='workspace.booking')),
            ],
        ),
    ]
