# Generated by Django 4.0.4 on 2022-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_plan_space_alter_booking_plan_alter_booking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
